version: "2"

services:
  alwaysconnected:
    image: kvaes/tasmaniantraders-iot-connectedvehicle:latest
    environment:
      - iothubconnectionstring="test"
      - offlineMin=0
      - offlineMax=1
      - interval=15
  badlyconnected:
    image: kvaes/tasmaniantraders-iot-connectedvehicle:latest
    environment:
      - iothubconnectionstring="test"
      - offlineMin=10
      - offlineMax=60
      - interval=15
